container_image        = osdf:///ospool/uc-shared/public/osg-training/tutorial-minimap2/software/minimap2_08OCT2025_v1.sif

executable             = run_minimap2.sh
arguments              = M_novaeangliae_fasta.mmi subset_ab_m_novaeangliae.fastq

transfer_input_files   = osdf:///ospool/uc-shared/public/osg-training/tutorial-minimap2/inputs/M_novaeangliae_fasta.mmi, inputs/subset_ab_m_novaeangliae.fastq
should_transfer_files  = YES

transfer_output_files  = mapped_subset_ab_m_novaeangliae.fastq_reads_to_genome_sam_sorted.bam
transfer_output_remaps = "mapped_subset_ab_m_novaeangliae.fastq_reads_to_genome_sam_sorted.bam = outputs/mapped_subset_ab_m_novaeangliae.fastq_reads_to_genome_sam_sorted.bam"

output                 = ./logs/$(Cluster)_$(Process)_mapping_subset_ab_m_novaeangliae.fastq_step2.out
error                  = ./logs/$(Cluster)_$(Process)_mapping_subset_ab_m_novaeangliae.fastq_step2.err
log                    = ./logs/$(Cluster)_mapping_step2.log

request_cpus           = 2
request_disk           = 5 GB
request_memory         = 10 GB

queue 1